"""Alembic environment.

Migrations are applied by running ``alembic upgrade head`` from the api image
(``WORKDIR /app``) — as a Helm pre-install/pre-upgrade hook in the cluster and
as the one-shot ``migrate`` service in docker compose. Revisions are always
written by hand and committed; nothing is autogenerated at runtime.
"""

from __future__ import annotations

from sqlalchemy import create_engine

from alembic import context
from app.config import get_settings
from app.logging_config import configure_logging
from app.models import Base

settings = get_settings()
configure_logging(
    settings.log_level,
    service="migrate",
    git_sha=settings.git_sha,
    pr_number=settings.pr_number,
)

config = context.config
target_metadata = Base.metadata


def run_migrations_offline() -> None:
    """Emit SQL to stdout instead of talking to a database."""
    context.configure(
        url=settings.database_url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Apply migrations against the live database.

    The engine is built straight from ``DATABASE_URL`` rather than through
    ``engine_from_config`` so a password containing ``%`` cannot trip over
    configparser interpolation.
    """
    engine = create_engine(settings.database_url, poolclass=None, future=True)
    with engine.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
        )
        with context.begin_transaction():
            context.run_migrations()
    engine.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
